### ISSUE TITLE
completely broken, doesnt work anymore

### ISSUE THREAD

**Issue by FlR0X** [Mana42138/Neverlose-UI#1]
just errors lol
![image](https://github.com/Mana42138/Neverlose-UI/assets/86130692/a711eb43-77c6-4bdc-b0a6-fdb65434c5da)

**Comment by Mana42138** [comment]
your executor doesn't support http requests

- I can remove build versions if needed since byfron has been spreading rapidly

Edit: Removed Get Requests from pastebin

**Comment by FlR0X** [comment]
it does support http requests because its fluxus, i removed it in my fork of your ui (i gave credits dw) and it worked fine, thanks for responding tho

**Comment by TNEGA69** [comment]
> it does support http requests because its fluxus, i removed it in my fork of your ui (i gave credits dw) and it worked fine, thanks for responding tho

pls make a comeback we miss you all...

**Comment by TNEGA69** [comment]
> it does support http requests because its fluxus, i removed it in my fork of your ui (i gave credits dw) and it worked fine, thanks for responding tho
Bitte Firox, komm wieder. Du wolltest ja "das große Geld" verdienen. Ich habe einen guten Plan. Bitte antworte mir auf Discord Mein Name ist: "tnegaprime" Hoffentlich kennst du mich noch.
